### ISSUE TITLE
Support of reCAPTCHA API v2

### ISSUE THREAD

**Issue by evnik** [tanveery/recaptcha-net#1]
You maybe know, I've made a fork of the project and have implemented support of the latest version of the reCAPTCHA API (including the new widget support) with keeping of full backward compatibility with the _Recaptcha for .NET_ assemblies. Source code is also mirrored on GitHub at https://github.com/evnik/reCAPTCHA4net.
I believe my changes could be ported back to the _Recaptcha for .NET_ project. Let me know if you interested in, and I will create a pull request.

**Comment by tanveery** [comment]
Thank you. Please go ahead.
