### ISSUE TITLE
Strong Name Signing

### ISSUE THREAD

**Issue by doowruc** [tanveery/recaptcha-net#12]
Please add strong name signing

Many thanks

**Comment by tanveery** [comment]
The new version is released on GitHub and Nuget. It includes strong name signing and it includes seamless support for both version 1 and 2 of Google's reCAPTCHA. All you need is to set value 1 or 2 for recapchaApiVersion app settings of web.config file.

**Comment by doowruc** [comment]
Excellent! Implemented just now, all confirmed wrking

Thank you
