### ISSUE TITLE
Documentation errors

### ISSUE THREAD

**Issue by kckempf** [tanveery/recaptcha-net#13]
There are errors in the documentation, the biggest of which is in the description of the security key configuration, where the "key" attribute is mistakenly labeled "name'.

**Comment by tanveery** [comment]
Thanks for raising this issue. It is fixed now.

BTW, the new version is released on GitHub and Nuget. It seamlessly supports both version 1 and 2 of Google's reCAPTCHA. All you need is to set value 1 or 2 for recapchaApiVersion app settings of web.config file. Other changes include strong name signing, bug fixes and code optimization.
