### ISSUE TITLE
@Html.Recaptcha(publicKey:"Your site key", privateKey:"Your secret key") Doesn't work in view

### ISSUE THREAD

**Issue by TylerSustare** [tanveery/recaptcha-net#26]
The web config method works just fine for me. But our organization needs this to bypass the web config.

From the readme this should be working, but I get a 
Error   CS1739  The best overload for 'Recaptcha' does not have a parameter named 'privateKey'

**Comment by gir489** [comment]
I think your problem is you're setting the wrong variable. This is how I'm doing it in the control.

`base.PrivateKey = System.Configuration.ConfigurationManager.AppSettings["recaptchaPrivateKey"];`

**Comment by robertba** [comment]
No, this is an issue.  Using v2.1.  

I need to set the public key at runtime and not have the value exist in "web.config".

The signature for creating the Recaptcha control in MVC looks like:

        public static IHtmlString Recaptcha(this HtmlHelper htmlHelper, string publicKey = "{recaptchaPublicKey}", RecaptchaTheme theme = RecaptchaTheme.Red, string language = null, int tabIndex = 0, RecaptchaDataType? dataType = default(RecaptchaDataType?), RecaptchaDataSize? dataSize = default(RecaptchaDataSize?), SslBehavior useSsl = SslBehavior.SameAsRequestUrl, string apiVersion = "{recaptchaApiVersion}");

Note there is no entry for the private key as the documentation states.  Am I doing something wrong or what changed?  Very disappointing to get it implemented (using web.config as a shortcut) then when it came time to set things up to work from settings the library didn't deliver what the docs said.

**Comment by vishnu4** [comment]
yeah, putting it in the view doesn't seem to work right, but inside the MVC controller you can change the code to:
this.GetRecaptchaVerificationHelper(reCaptchaPrivateKey);
