### ISSUE TITLE
reCaptcha lib v2.1 shows old style captcha

### ISSUE THREAD

**Issue by Ori4** [tanveery/recaptcha-net#40]
I am using Recaptcha.Web.dll v2.1.0.0 but, when run, shows the older version, i.e., 2 words instead of the newer "I am not a robot" with checkbox.
Any ideas why?
Help most appreciated.

Ori

**Comment by dhbotha** [comment]
I am sitting with the same issue.
Were you able to solve this? And how?
DHB

**Comment by classdroogies** [comment]
You must set ApiVersion to 2, default is 1. See webconfig file in sample code.

https://github.com/tanveery/recaptcha-net/blob/master/samples/RecaptchaWebFormSample/Web.config

**Comment by tanveery** [comment]
Thank you @classdroogies for responding to the queries from @Ori4 and @dhbotha
