### ISSUE TITLE
Enhancement: update to use new recaptcha widget.

### ISSUE THREAD

**Issue by infamousdutch** [tanveery/recaptcha-net#5]
ReCaptcha just recently updated their widget.  Might want to update this to use the newer widget

**Comment by evnik** [comment]
Support of the new widget is implemented in #3 which is waiting to be merged. Until that you can temporary use [reCAPTCHA4net](https://recaptcha4net.codeplex.com).

**Comment by tanveery** [comment]
This will be implemented in the next major release (v2.0.0.0).

**Comment by tanveery** [comment]
The new version is released on GitHub and Nuget. It seamlessly supports both version 1 and 2 of Google's reCAPTCHA. All you need is to set value 1 or 2 for recapchaApiVersion app settings of web.config file. Other changes include strong name signing, bug fixes and code optimization.
