### ISSUE TITLE
Project not running on local

### ISSUE THREAD

**Issue by akshit1823** [tanveery/recaptcha-net#62]
Project not running on local
![image](https://user-images.githubusercontent.com/61692699/126308779-82eff3dc-d2c7-446f-9ac3-5ee265bce114.png)

**Comment by akshit1823** [comment]
![image](https://user-images.githubusercontent.com/61692699/126309321-5702a886-83d0-4f33-aa8e-cf01f9666da2.png)

**Comment by tanveery** [comment]
Please remove the .pfx files or add your own.
