### ISSUE TITLE
reCAPTCHA v2

### ISSUE THREAD

**Issue by babakarj** [tanveery/recaptcha-net#8]
How is it possible to use reCAPTCHA v2 with this library?

https://support.google.com/recaptcha/#6080904

**Comment by hikalkan** [comment]
+1

**Comment by evnik** [comment]
As mentioned in #5, support of reCAPTCHA V2 (new widget) is implemented in #3, which is waiting to be merged. For now you can temporarily use [reCAPTCHA4net](https://recaptcha4net.codeplex.com).

**Comment by tanveery** [comment]
The new version is released on GitHub and Nuget. It seamlessly supports both version 1 and 2 of Google's reCAPTCHA. All you need is to set value 1 or 2 for recapchaApiVersion app settings of web.config file. Other changes include strong name signing, bug fixes and code optimization.

**Comment by hikalkan** [comment]
This is very good new. Thank you very much :)

**Comment by tiesont** [comment]
I notice the NuGet package defaults to use version 1 in the web.config - is that intentional? If not, Google seems to be pushing everyone to v.2, so it may be worth updating the package.
